name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  main-ci:
    uses: osfanbuff63/action-workflows/.github/workflows/mcfunction.yml@v1
    with:
      version: v0.1.0
      files: |
        assets/
        data/
        pack.mcmeta
        pack.png
        LICENSE.md
