name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@2e205a28d0e1da00c5f53b161f4067b052c61f34
      with:
        egress-policy: block
        allowed-endpoints: >
          api.github.com:443

    - uses: actions/first-interaction@1dbfe1ba5525b8257e1f259b09745bee346d62d8
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome to the repository! Make sure to read the README.md specifically the Contributing section, before continuing, if you have not already!'
        pr-message: 'Welcome to the repository! Make sure to read the README.md, specifically the Contributing section, before continuing, if you have not already! And thanks for helping out with a PR! It is very helpful sometimes :)'
