name: Publish release (beta)
on: 
  push:
    tags:
     - 'v*-beta*'
     - 'v*-alpha*'
  workflow_dispatch:
permissions:
  contents: read

jobs:
  release:
    uses: osfanbuff63/action-workflows/.github/workflows/mcfunction-release.yml
    with:
      version: v0.1.0-alpha2
      files: |
        assets/
        data/
        pack.mcmeta
        pack.png
        LICENSE.md
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
