name: Publish release (beta)
on: 
  push:
    tags:
     - 'v*-beta*'
     - 'v*-alpha*'
  workflow_dispatch:
permissions:
  contents: read

jobs:
   upload-normal:
    name: Create non-optimized datapack
    runs-on: ubuntu-latest
    steps:
     - name: Harden Runner
       uses: step-security/harden-runner@74b568e8591fbb3115c70f3436a0c6b0909a8504
       with:
         egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

     - name: Clone repository
       uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
       with:
         fetch-depth: 0
     - name: Check commands
       uses: mcbeet/check-commands@740e5fb3c385a5a5775f9ab6c963745200cb71aa
       with:
          source: .
          minecraft: 1.18
     - name: Check JSON
       uses: ocular-d/json-linter@7d3716a34bcd6fcc5b3b38141a21b9e02da6531d
     - name: Upload artifact
       uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
       with:
         path: |
             assets/
             data/
             pack.mcmeta
             pack.png
         name: ws-datapack v0.1.0-alpha1
         
   upload-optimized-datapack:
    permissions:
      actions: read  # for ComunidadAylas/PackSquash-action to get latest artifact
    name: Optimize datapack
    runs-on: ubuntu-latest
    needs: upload-normal
    steps:
     - name: Harden Runner
       uses: step-security/harden-runner@74b568e8591fbb3115c70f3436a0c6b0909a8504
       with:
         egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

     - name: Download normal pack
       uses: actions/download-artifact@076f0f7dd036d87e8e04f5f00d614e790308961b
       with:
         name: ws-datapack v0.1.0-alpha1
         path: ./
     - name: Run PackSquash
       uses: ComunidadAylas/PackSquash-action@c3641c92cc0e4ff6ee88db9a34b6a2d48fcfcc71
       with:
          path: ./
          token: ${{ secrets.GITHUB_TOKEN }}
          minify_json_files: true
          validate_pack_metadata_file: true
          allow_optifine_mod: true
          delete_bloat_json_keys: true
          artifact_name: 'optimized-ws-datapack v0.1.0-alpha1'
          never_store_squash_times: true


   create-release:
     permissions:
       contents: write  # for softprops/action-gh-release to create GitHub release
       issues: read  # for heinrichreimer/github-changelog-generator-action to fetch issues and labels
       pull-requests: read  # for heinrichreimer/github-changelog-generator-action to fetch PRs and labels
     name: Create release
     needs: [upload-normal,upload-optimized-datapack]
     runs-on: ubuntu-latest
     steps:
       - name: Harden Runner
         uses: step-security/harden-runner@74b568e8591fbb3115c70f3436a0c6b0909a8504
         with:
           egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
       - name: Get the version
         id: get_version
         run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
       - name: Checkout repo
         uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
         with:
           token: ${{ secrets.GH_TOKEN }}
       - name: Generate release changelog
         uses: heinrichreimer/github-changelog-generator-action@6653241a44afb59146f719f322005de49a5c3b38
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
           dateFormat: '%m/%d/%Y'
       - name: Make directory
         run: mkdir changelog
       - name: Generate release changelog (Single tag)
         uses: heinrichreimer/github-changelog-generator-action@6653241a44afb59146f719f322005de49a5c3b38
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
           dateFormat: '%m/%d/%Y'
           onlyLastTag: true
           output: /changelog/CHANGELOG.md           
       - name: Download normal pack
         uses: actions/download-artifact@076f0f7dd036d87e8e04f5f00d614e790308961b
         with:
           name: ws-datapack v0.1.0-alpha1
       - name: Zip pack
         run: zip 'ws-datapack v0.1.0-alpha1' -r data assets pack.mcmeta 
       - name: Delete datapack
         run: rm -r data assets pack.mcmeta 
       - name: Download optimized pack
         uses: actions/download-artifact@076f0f7dd036d87e8e04f5f00d614e790308961b
         with:
           name: optimized-ws-datapack v0.1.0-alpha1
       - name: Zip optimized pack
         run: |
           mkdir packsquash
           unzip -f pack.zip -d /packsquash/
           mv LICENSE.md ./packsquash/
           cd packsquash
           zip -r 'optimized-ws-datapack v0.1.0-alpha1' . -i data assets pack.mcmeta LICENSE.md
           mv 'optimized-ws-datapack v0.1.0-alpha1' ..
           cd ..
       - name: Release
         uses: softprops/action-gh-release@50195ba7f6f93d1ac97ba8332a178e008ad176aa
         with:
           files: |
             *.zip
           body_path: CHANGELOG.md
       - name: Commit changes
         run: |
            echo ${GITHUB_REF#refs/*/}
            git config --local user.name "actions-user"
            git config --local user.email "action@github.com"
            git add CHANGELOG.md
            git commit -m "[ci skip] Updated CHANGELOG.md for ${{ steps.get_version.outputs.VERSION }}"
            git push origin HEAD:master
            
